# -*- coding: utf-8 -*-
"""
06_framework.py — LegalGraphRAG + 4-agent pipeline for the G1-G6 experiments.

Agents:
  A1 Difficulty Planner   (deterministic: target FRE band + term policy per level)
  A2 Material Generator   (SLM: Qwen3-4B untuned | Qwen3.5-4B + SFT/GRPO adapter)
  A3 Quality Evaluator    (verifiable reward stack + NLI gate, reuses 05 functions)
  A4 Feedback Optimizer   (corrective instruction -> regenerate, <=3 attempts)

RAG (LegalGraphRAG-lite): term definitions + dense (MiniLM/FAISS) + graph (shared-term)
retrieval fused by weighted score, top-2 passages; KB = train+val only (no test leak).

Config to G groups:
  G1  qwen3-4b                (zero-shot, no rag, no agents)
  G2  qwen3-4b          --rag
  G3  qwen3-4b                 --agents
  G4  qwen3-4b          --rag --agents
  G5  qwen35-sft        --rag --agents
  G6  qwen35-grpo       --rag --agents   (default grpo adapter = v2 if present else v1)

Output: JSONL results/{tag}.jsonl with per-sample metrics.
"""
import os, sys, json, re, types, argparse, random, time
import numpy as np
import torch

sys.stdout.reconfigure(encoding='utf-8', errors='replace')
DATA = "/path/to/legal_english/data"
MODELS = "/path/to/legal_english/models"
RESULTS = "/path/to/legal_english/results"

LEVEL_TARGET_FRE = {"beginner": 63.0, "intermediate": 45.0, "advanced": 26.0}
W = {"fmt": 0.15, "diff": 0.20, "term": 0.15, "copy": 0.25, "faith": 0.25}
THINK_MARKERS = ["thinking process", "analyze the request", "thought process",
                 "let me think", "思考过程", "分析需求", "here's a thinking", "<think"]
META_PATTERNS = [
    "this rewrite", "this version", "this simplified", "this explanation",
    "in summary", "to summarize", "in conclusion", "as requested",
    "i hope this", "hope this helps", "i have rewritten", "i've rewritten",
    "the above", "this is a simplified", "this keeps the main ideas",
    "it simplifies", "the original legal text", "i have simplified",
    "here is", "below is", "this passage", "i tried", "let me know",
    "the user wants", "i need to", "i must", "i should", "i will structure",
    "the text covers", "the source text", "the provided text", "the input text",
    "reading difficulty", "reading level", "reading ease", "previous attempt",
    "the legal terms", "legal terms like", "let me structure", "drafting plan",
    "the rules are", "the goal is", "the target is", "i'm going to",
    "i am going to", "i plan to", "i understand", "the instruction says",
    "the retrieved", "key elements", "the following legal text", "here's my",
    "drafting", "analysis", "the source material", "original text",
    "key points", "overview", "the rules cover", "previous version",
    "the following are", "please note",
]

# Leading-commentary block detection. An output that begins with one of these
# phrases is treated as meta-commentary and stripped before any metric is
# computed; if nothing survives, the attempt is a pure-commentary failure
# (fmt = 0, regenerated by the gate when --agents).
#
# DELIBERATE DESIGN: only STRONG meta signals live here, and _clean_and_removed
# matches them against the FIRST ~150 chars of a block (preambles are short).
# Weak/ambiguous phrases that can appear inside real legal prose ("here is",
# "below is", "the following are", "the rules are", "please note") are NOT in
# this list: a false positive destroys a good rewrite, whereas a false negative
# merely keeps a preamble that r_fmt still penalises. Legal bullet glossaries
# (e.g. "**Simple explanations:**" + "- Term: ...") are legal content and kept.
CLEAN_BLOCK_RE = re.compile(
    r"(the user wants|this is a legal text rewriting task|i need to|i must|i will|"
    r"i should|i would|let me|the source text|the provided text|the input text|"
    r"reading difficulty|reading level|reading ease|previous attempt|the legal terms|"
    r"legal terms like|i have rewritten|this rewrite|my goal|my rewrite|"
    r"the target is|the goal is|i'm going to|i am going to|i plan to|i understand|"
    r"drafting plan|the instruction says|the following legal text|"
    r"here's my|here is my|below is my|^drafting|^analysis|^overview|"
    r"^summary|the source material|original text analysis)", re.I)


# Short leading "label" lines that preface a rewrite but are themselves
# meta-commentary (e.g. "Drafting:", "**Original Text Analysis:**").
LABEL_RE = re.compile(
    r"^\*{0,2}(drafting|analysis|overview|summary|notes?|comments?|rewritten"
    r"|simplified (version|text)|the rewrite|output|result|response)"
    r"\s*[:.\-]?\s*\*{0,2}\s*$", re.I)


def _is_planning_item(b):
    """A short bullet/numbered item (typical of a planning list) has few words
    and no internal multi-sentence punctuation. Long legal paragraphs survive."""
    return (len(b.split()) < 30
            and not re.search(r"[.!?]\s+[A-Z]", b))


def _clean_and_removed(rew):
    """Return (cleaned_text, removed_any). removed_any=True when substantive
    leading content (a label line, a meta-commentary block, or a planning item)
    was dropped from the start of rew -- NOT mere whitespace normalization
    (single newlines inside a block are preserved, as for legal bullet lists).
    """
    blocks = [b.strip() for b in re.split(r"\n\s*\n", rew) if b.strip()]
    kept, started, in_preamble, removed = [], False, False, False
    for b in blocks:
        if not started:
            # strip a single leading label line ("Drafting:", "**Analysis:**",
            # "The rewrite:") before deciding whether the rest is commentary.
            lines = b.split("\n")
            if len(lines) > 1 and LABEL_RE.match(lines[0].strip()):
                b = " ".join(lines[1:]).strip()
                if len(b.split()) < 8:
                    removed = True
                    continue      # label + short fragment -> still commentary
                removed = True
            is_meta = bool(CLEAN_BLOCK_RE.search(b[:150]))
            if is_meta:
                removed = True
                in_preamble = True
                continue
            if in_preamble and (b.startswith(("-", "*", "•"))
                                or re.match(r"^\d+[\.\)]", b)) \
                    and _is_planning_item(b):
                removed = True
                continue          # bulleted planning continuation
            started = True
        kept.append(b)
    out = " ".join(kept).strip()
    if len(out.split()) < 8:
        out = ""
        if blocks:
            removed = True        # too fragmentary to be a rewrite
    return out, removed


def clean_output(rew):
    """Strip any leading meta-commentary/planning block, returning only the
    actual rewrite. Returns '' if nothing legal-prose survived (pure commentary).
    """
    return _clean_and_removed(rew)[0]


def stripped_info(rew):
    """True iff clean_output drops substantive leading content from rew (as
    opposed to normalizing whitespace). Pure-commentary outputs -> True."""
    return _clean_and_removed(rew)[1]

SYSTEM = ("You are a legal English educator. You rewrite legal texts into clear, "
          "level-appropriate versions for English learners. You always output "
          "ONLY the requested rewrite, starting directly with it.")
USER = ("Rewrite the following legal text into a {lv}-level version for English "
        "learners. Preserve legal meaning and key legal terms.\n"
        "{diff_inst}\n{rag_ctx}{src}")
FEEDBACK = ("Your previous rewrite was rejected by the quality check. Improve it "
            "according to these notes and produce a NEW rewrite only:\n{notes}")


# ---------------- metric / reward helpers (mirror 05_grpo_train.py) ----------------
def enable_peft_on_text_model(lm):
    if not hasattr(lm, "prepare_inputs_for_generation"):
        def _prep(self, input_ids, past_key_values=None, attention_mask=None, **kwargs):
            if past_key_values is not None:
                input_ids = input_ids[:, -1:]
            out = {"input_ids": input_ids, "attention_mask": attention_mask,
                   "past_key_values": past_key_values}
            out.update(kwargs)
            return out
        lm.prepare_inputs_for_generation = types.MethodType(_prep, lm)
    return lm


def _syllables(w):
    w = w.lower()
    if len(w) <= 3:
        return 1
    syl = len(re.findall(r"[aeiouy]+", w))
    if w.endswith("e"):
        syl -= 1
    return max(1, syl)


def _num_sents(text):
    punct = len(re.findall(r"[.!?]+", text))
    lines = sum(1 for ln in text.split("\n") if ln.strip())
    return max(punct, lines, 1)


def flesch(text):
    words = re.findall(r"[A-Za-z']+", text)
    if not words:
        return 0.0
    sents = _num_sents(text)
    syl = sum(_syllables(w) for w in words)
    return 206.835 - 1.015 * (len(words) / sents) - 84.6 * (syl / len(words))


def r_fmt(rew, src):
    r = 1.0
    if not rew or len(rew.split()) < 5:
        return 0.0
    low = rew.lower()
    if any(m in low for m in THINK_MARKERS):
        r -= 0.5
    if "rewrite the following" in low[:60]:
        r -= 0.3
    hits = sum(1 for m in META_PATTERNS if m in low)
    if hits:
        r -= min(0.6, 0.3 * hits)
    if abs(len(rew.split()) - len(src.split())) > 0.9 * len(src.split()):
        r -= 0.3
    return max(0.0, min(1.0, r))


def r_diff(rew, lv):
    fre = flesch(rew)
    target = LEVEL_TARGET_FRE[lv]
    return max(0.0, min(1.0, 1.0 - abs(fre - target) / 20.0))


def r_term(rew, src, terms):
    src_low, rew_low = src.lower(), rew.lower()
    present = [t for t in terms if t.lower() in src_low]
    if not present:
        return 1.0
    kept = sum(1 for t in present if t.lower() in rew_low)
    return kept / len(present)


def r_copy(rew, src):
    rw = re.findall(r"[a-z']+", rew.lower())
    sw = re.findall(r"[a-z']+", src.lower())
    if len(rw) < 8 or len(sw) < 8:
        return 0.5
    rset = set(tuple(rw[i:i + 3]) for i in range(len(rw) - 2))
    sset = set(tuple(sw[i:i + 3]) for i in range(len(sw) - 2))
    if not sset:
        return 1.0
    overlap = len(rset & sset) / len(sset)
    return max(0.0, min(1.0, 1.0 - max(0.0, (overlap - 0.4) / 0.4)))


def r_faith(rew, src, nli_model, nli_tok, nli_dev):
    """Return full DeBERTa-v3 NLI 3-class probs (entail, neutral, contradiction).
    Label order: entailment=0, neutral=1, contradiction=2."""
    try:
        enc = nli_tok(src[:4000], rew[:4000], return_tensors="pt",
                      truncation=True, max_length=512).to(nli_dev)
        with torch.no_grad():
            out = nli_model(**enc)
        p = torch.softmax(out.logits, dim=-1)[0].tolist()
        return (float(p[0]), float(p[1]), float(p[2]))
    except Exception:
        return (0.0, 0.0, 0.0)


def rewards(rew, src, lv, terms, nli_model, nli_tok, nli_dev):
    rf, rd = r_fmt(rew, src), r_diff(rew, lv)
    rt, rc = r_term(rew, src, terms), r_copy(rew, src)
    ent, neu, con = r_faith(rew, src, nli_model, nli_tok, nli_dev)
    tot = (W["fmt"] * rf + W["diff"] * rd + W["term"] * rt +
           W["copy"] * rc + W["faith"] * ent)
    nli = {"entail": round(ent, 4), "neutral": round(neu, 4), "contra": round(con, 4)}
    return tot, {"fmt": rf, "diff": rd, "term": rt, "copy": rc, "faith": ent}, \
        flesch(rew), nli


# ---------------- Agent 1: Difficulty Planner (deterministic) ----------------
def plan_difficulty(lv):
    if lv == "beginner":
        return ("Target: very easy learner text (reading ease score about 60-65). "
                "Use short sentences and common everyday words. Explain legal terms "
                "in simple words when you keep them.")
    if lv == "intermediate":
        return ("Target: moderately challenging text (reading ease score about 40-50). "
                "Keep precise legal vocabulary and formal structure, but clarify "
                "complex constructions.")
    return ("Target: advanced legal text (reading ease score about 20-30). "
            "Preserve formal legal register, long precise sentences and all terms.")


# ---------------- RAG: LegalGraphRAG-lite ----------------
class MiniLMEmbed:
    """Direct HF AutoModel embedding (sentence_transformers version mismatch)."""
    def __init__(self, model_dir, dev="cuda:0"):
        from transformers import AutoModel, AutoTokenizer
        self.tok = AutoTokenizer.from_pretrained(model_dir)
        self.model = AutoModel.from_pretrained(model_dir).to(dev).eval()
        self.dev = dev

    def encode(self, texts, normalize_embeddings=True, batch_size=32,
               show_progress_bar=False):
        outs = []
        for i in range(0, len(texts), batch_size):
            batch = texts[i:i + batch_size]
            enc = self.tok(batch, padding=True, truncation=True, max_length=256,
                           return_tensors="pt").to(self.dev)
            with torch.no_grad():
                out = self.model(**enc)
            mask = enc["attention_mask"].unsqueeze(-1)
            pooled = (out.last_hidden_state * mask).sum(1) / mask.sum(1)
            if normalize_embeddings:
                pooled = torch.nn.functional.normalize(pooled, dim=1)
            outs.append(pooled.cpu().numpy())
        return np.concatenate(outs, axis=0)


class RagIndex:
    def __init__(self, kb, emb_model, terms):
        self.kb = kb                      # list of {id, text} train+val only
        self.terms = terms                # list of term strings
        self.term_defs = {}
        self.emb_model = emb_model
        self.texts = [s["text"] for s in kb]
        self.ids = [s["id"] for s in kb]
        embs = emb_model.encode(self.texts, normalize_embeddings=True,
                                batch_size=32, show_progress_bar=False)
        import faiss
        self.index = faiss.IndexFlatIP(embs.shape[1])
        self.index.add(np.ascontiguousarray(embs.astype("float32")))
        self.doc_terms = [self._terms_in(t) for t in self.texts]
        self._load_defs()

    def _load_defs(self):
        c = json.load(open(os.path.join(DATA, "corpus_v2.json"), encoding="utf-8"))
        raw = c.get("terms", [])
        for t in raw:
            if isinstance(t, dict):
                self.term_defs[t.get("term", "")] = t.get("definition", "")
            else:
                self.term_defs[t] = ""

    def _terms_in(self, text):
        low = text.lower()
        return [t for t in self.terms if t.lower() in low]

    def retrieve(self, src, k=2):
        """dense + graph(shared-term) fusion, exclude source-like ids."""
        q = self.emb_model.encode([src], normalize_embeddings=True).astype("float32")
        scores, idx = self.index.search(q, min(8, len(self.texts)))
        cand = {}
        for s, i in zip(scores[0], idx[0]):
            sid = self.ids[i]
            if sid in src:            # don't retrieve the source itself
                continue
            cand[sid] = 0.7 * float(s) + 0.3 * 0.0
        # graph signal: snippets sharing terms with the source
        st = self._terms_in(src)
        if st:
            for i, doc_ts in enumerate(self.doc_terms):
                shared = len(set(st) & set(doc_ts))
                if shared and self.ids[i] not in src:
                    sid = self.ids[i]
                    cand[sid] = cand.get(sid, 0.0) + 0.4 * (shared / max(1, len(st)))
        top = sorted(cand.items(), key=lambda kv: -kv[1])[:k]
        return [self.kb[self.ids.index(sid)] for sid, _ in top]

    def term_context(self, src):
        st = self._terms_in(src)
        out = []
        for t in st[:6]:
            d = self.term_defs.get(t, "")
            out.append(f'- Term "{t}": {d}' if d else f'- Term "{t}"')
        return "\n".join(out)


def build_rag_ctx(rag, src):
    ctx = []
    tc = rag.term_context(src)
    if tc:
        ctx.append("Key legal terms used in this text:\n" + tc)
    passages = rag.retrieve(src)
    if passages:
        ctx.append("Related legal passages for context:")
        for p in passages:
            ctx.append("> " + p["text"][:280].replace("\n", " "))
    if ctx:
        return "The following legal knowledge is retrieved to assist generation:\n" + \
               "\n\n".join(ctx) + "\n\n"
    return ""


# ---------------- Agent 3/4: gate + corrective feedback ----------------
def gate_feedback(parts, fre, lv, src, terms, rew):
    """Return (pass, notes). pass=False triggers regeneration with notes."""
    notes = []
    if parts["faith"] < 0.35:
        notes.append("FIDELITY: your rewrite lost or changed legal facts; preserve every "
                     "legal rule from the source exactly, do not add or drop obligations.")
    if parts["diff"] < 0.40:   # |fre - target| > 12 points -> ask for another pass
        tgt = LEVEL_TARGET_FRE[lv]
        if fre > tgt:
            notes.append("DIFFICULTY: still too hard; use shorter sentences and simpler "
                         "everyday words.")
        else:
            notes.append("DIFFICULTY: still too easy/vague; keep more precise legal "
                         "wording and structure.")
    if parts["term"] < 0.5:
        present = [t for t in terms if t.lower() in src.lower()]
        kept = [t for t in present if t.lower() not in rew.lower()]
        if kept:
            notes.append("TERMS: keep these key legal terms verbatim: " + ", ".join(kept[:6]))
    if parts["fmt"] < 0.7:
        notes.append("FORMAT: output ONLY the rewrite text, no explanation or preamble.")
    return (len(notes) == 0, "; ".join(notes))


# ---------------- main ----------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", choices=["qwen3-4b", "qwen35-sft", "qwen35-grpo"],
                    required=True)
    ap.add_argument("--rag", action="store_true")
    ap.add_argument("--agents", action="store_true")
    ap.add_argument("--n-test", type=int, default=50)
    ap.add_argument("--max-attempts", type=int, default=3)
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--tag", default=None, help="output jsonl tag (default = G<n>)")
    ap.add_argument("--adapter", default=None,
                    help="override adapter path for qwen35-sft/grpo evals (ablation adapters)")
    ap.add_argument("--levels", default="beginner,intermediate",
                    help="comma-separated difficulty levels (beginner,intermediate,advanced)")
    ap.add_argument("--kb-exclude-title", default="",
                    help="exclude KB passages whose title contains this substring (OOD doc holdout)")
    ap.add_argument("--kb-only-prefix", default="",
                    help="restrict KB to passages whose id starts with this prefix (OOD mismatch)")
    ap.add_argument("--kb-frac", type=float, default=1.0,
                    help="use a random fraction of the KB (seeded) for size robustness")
    ap.add_argument("--src-prefix-filter", default="",
                    help="only test sources whose id starts with this prefix")
    ap.add_argument("--title-filter", default="",
                    help="only test sources whose title contains this substring")
    args = ap.parse_args()
    random.seed(args.seed); np.random.seed(args.seed)
    torch.manual_seed(args.seed); torch.cuda.manual_seed_all(args.seed)
    rng = random.Random(args.seed)
    os.makedirs(RESULTS, exist_ok=True)
    from transformers import AutoModelForCausalLM, AutoModelForImageTextToText, \
        AutoTokenizer, BitsAndBytesConfig
    from peft import PeftModel

    tag = args.tag or f"model-{args.model}-rag{int(args.rag)}-agents{int(args.agents)}"
    print(f"=== {tag}: model={args.model} rag={args.rag} agents={args.agents} ===",
          flush=True)

    bnb = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.bfloat16,
                             bnb_4bit_quant_type="nf4", bnb_4bit_use_double_quant=True)

    # ---- SLM ----
    if args.model == "qwen3-4b":
        mid = os.path.join(MODELS, "Qwen3-4B-Instruct-2507")
        slm = AutoModelForCausalLM.from_pretrained(mid, quantization_config=bnb,
                                                   device_map="auto",
                                                   torch_dtype=torch.bfloat16)
        print("SLM: Qwen3-4B-Instruct (untuned)", flush=True)
    else:
        mid = os.path.join(MODELS, "Qwen3.5-4B")
        slm = AutoModelForImageTextToText.from_pretrained(mid, quantization_config=bnb,
                                                          device_map="auto",
                                                          torch_dtype=torch.bfloat16)
        if args.model == "qwen35-sft":
            adp = args.adapter or os.path.join(MODELS, "sft_qwen35_lora")
        else:
            adp = (args.adapter or
                   (os.path.join(MODELS, "grpo_qwen35_lora_v2")
                    if os.path.isdir(os.path.join(MODELS, "grpo_qwen35_lora_v2"))
                    else os.path.join(MODELS, "grpo_qwen35_lora")))
        lm = slm.model.language_model
        enable_peft_on_text_model(lm)
        lm = PeftModel.from_pretrained(lm, adp, is_trainable=False)
        slm.model.language_model = lm
        print(f"SLM: Qwen3.5-4B + adapter {adp}", flush=True)
    slm.eval()
    tok = AutoTokenizer.from_pretrained(mid, use_fast=True)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token

    # ---- NLI for r_faith / gate ----
    from transformers import AutoModelForSequenceClassification
    nli_dev = "cuda:0"
    nli_model = AutoModelForSequenceClassification.from_pretrained(
        os.path.join(MODELS, "NLI-DeBERTa-v3")).to(nli_dev).eval()
    nli_tok = AutoTokenizer.from_pretrained(os.path.join(MODELS, "NLI-DeBERTa-v3"))

    # ---- data ----
    split_path = os.environ.get("LEGAL_SPLIT_PATH", os.path.join(DATA, "split.json"))
    split = json.load(open(split_path, encoding="utf-8"))
    corpus = json.load(open(os.path.join(DATA, "corpus_v2.json"), encoding="utf-8"))
    raw_terms = corpus["terms"]
    terms = ([t["term"] if isinstance(t, dict) else t for t in raw_terms]
             if isinstance(raw_terms, list) else list(raw_terms.keys()))
    kb = [{"id": s["id"], "text": s["text"], "title": s.get("title", "")}
          for s in split["train"] + split["val"]]
    if args.kb_exclude_title:
        kb = [p for p in kb if args.kb_exclude_title not in p["title"]]
        print(f"OOD: KB excluded title '{args.kb_exclude_title}' -> {len(kb)} passages",
              flush=True)
    if args.kb_only_prefix:
        kb = [p for p in kb if p["id"].startswith(args.kb_only_prefix)]
        print(f"OOD: KB restricted to prefix '{args.kb_only_prefix}' -> {len(kb)} passages",
              flush=True)
    if args.kb_frac < 1.0:
        kb = rng.sample(kb, max(1, int(len(kb) * args.kb_frac)))
        print(f"OOD: KB fraction {args.kb_frac} -> {len(kb)} passages", flush=True)
    test_srcs = split["test"][:args.n_test]
    if args.src_prefix_filter:
        test_srcs = [s for s in test_srcs if s["id"].startswith(args.src_prefix_filter)]
    if args.title_filter:
        test_srcs = [s for s in test_srcs if args.title_filter in s.get("title", "")]
    test_srcs = test_srcs[:args.n_test]
    levels = [x.strip() for x in args.levels.split(",") if x.strip()]
    if not test_srcs:
        raise SystemExit(f"no test sources after filters (prefix={args.src_prefix_filter}, "
                         f"title={args.title_filter})")
    print(f"test sources: {len(test_srcs)} (n_test={args.n_test}), "
          f"levels={levels}, KB={len(kb)}", flush=True)

    # ---- RAG index (only if --rag) ----
    rag = None
    if args.rag:
        print("building RAG index (MiniLM over train+val)...", flush=True)
        emb_model = MiniLMEmbed(os.path.join(MODELS, "MiniLM-L6-v2"))
        rag = RagIndex(kb, emb_model, terms)
        print(f"RAG index ready: {len(kb)} passages, {len(terms)} terms", flush=True)

    # ---- run ----
    out_path = os.path.join(RESULTS, f"{tag}.jsonl")
    fout = open(out_path, "w", encoding="utf-8")
    gen_kw = dict(max_new_tokens=320, do_sample=True, temperature=0.9, top_p=0.95,
                  pad_token_id=tok.pad_token_id)
    t0 = time.time()
    n_done = 0
    n_total = len(test_srcs) * len(levels)
    for s in test_srcs:
        for lv in levels:
            t_item = time.time()
            src = s["text"]
            diff_inst = plan_difficulty(lv)
            rag_ctx = build_rag_ctx(rag, src) if rag else ""
            best = None
            attempt = 0
            notes_all = []
            while attempt < args.max_attempts:
                attempt += 1
                if attempt == 1:
                    user = USER.format(lv=lv, diff_inst=diff_inst, rag_ctx=rag_ctx, src=src)
                else:
                    user = (USER.format(lv=lv, diff_inst=diff_inst, rag_ctx=rag_ctx, src=src)
                            + "\n\n" + FEEDBACK.format(notes=notes_all[-1]))
                msgs = [{"role": "system", "content": SYSTEM},
                        {"role": "user", "content": user}]
                inp = tok.apply_chat_template(msgs, add_generation_prompt=True,
                                              chat_template_kwargs={"enable_thinking": False},
                                              return_tensors="pt")
                with torch.no_grad():
                    out = slm.generate(**inp.to(slm.device), num_return_sequences=1,
                                       **gen_kw)
                raw = tok.decode(out[0][inp["input_ids"].shape[1]:],
                                 skip_special_tokens=True).strip()
                rew = clean_output(raw)
                if not rew:
                    # pure commentary / no usable rewrite -> format failure
                    parts = {"fmt": 0.0, "diff": 0.0, "term": 0.0, "copy": 0.0,
                             "faith": 0.0}
                    fre = 0.0
                    nli = (0.0, 0.0, 1.0)
                else:
                    tot, parts, fre, nli = rewards(rew, src, lv, terms,
                                                   nli_model, nli_tok, nli_dev)
                stripped = stripped_info(raw)
                if best is None or tot > best["tot"]:
                    best = {"rew": rew, "tot": tot, "parts": parts, "fre": fre,
                            "attempts": attempt, "nli": nli, "stripped": stripped}
                if not args.agents:
                    break
                passed, note = gate_feedback(parts, fre, lv, src, terms, rew)
                if passed:
                    break
                notes_all.append(note)
            rec = {"id": s["id"], "lv": lv, "src": src, "rew": best["rew"],
                   "tot": round(best["tot"], 4), "parts": best["parts"],
                   "fre": round(best["fre"], 2), "attempts": best["attempts"],
                   "nli": best["nli"], "stripped": bool(best["stripped"]),
                   "sec": round(time.time() - t_item, 2)}
            fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
            n_done += 1
            if n_done % 20 == 0 or n_done == n_total:
                el = time.time() - t0
                print(f"  {n_done}/{n_total} done ({el/60:.1f} min)", flush=True)
    fout.close()
    print(f"done: {out_path} ({time.time()-t0:.0f}s)", flush=True)


if __name__ == "__main__":
    main()
